=== kb-dk/doms-server/ecm-lib/ecmLinks/src/main/resources/linkPatterns.xsd
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://doms.statsbiblioteket.dk/types/linkpattern/0/1/#"
           xmlns:tns="http://doms.statsbiblioteket.dk/types/linkpattern/0/1/#">
    <xs:element name="linkPatterns" type="tns:linkPatterns"/>
    <xs:complexType name="linkPatterns">
        <xs:sequence>
            <xs:element name="linkPattern" type="tns:linkPattern"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="linkPattern">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="replacements" type="tns:replacements" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="replacements">
        <xs:sequence>
            <xs:element name="replacement" type="tns:replacement" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="replacement">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="datastream" type="xs:string"/>
            <xs:element name="xpath" type="xs:string"/>
            <xs:element name="repeatable" type="xs:boolean" minOccurs="0"/>
            <xs:element name="prefix" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kb-dk/doms-server/ecmLinks/src/main/resources/linkPatternSample.xml
<lp:linkPatterns xmlns:lp="http://doms.statsbiblioteket.dk/types/linkpattern/0/1/#"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://doms.statsbiblioteket.dk/types/linkpattern/0/1/# linkPatterns.xsd">
    <lp:linkPattern>
        <lp:name>Get DVD file</lp:name>
        <lp:description>Get the DVD file from BTA</lp:description>
        <lp:value>http://statsbiblioteket.dk/BTA/{objectPid}/dvd/{title}</lp:value>
        <lp:replacements>
            <lp:replacement>
                <lp:key>title</lp:key>
                <lp:datastream>PBCORE</lp:datastream>
                <lp:xpath>/PBCoreDescriptionDocument/pbcoreTitle[titleType = 'titel']/title</lp:xpath>
            </lp:replacement>
        </lp:replacements>
    </lp:linkPattern>
</lp:linkPatterns>
